version: '3.9'

services: 
    node-app: 
        image: psg0018/node-app
        build: ./server
        ports:
            - "5000:5000"
        networks:
            - app-network
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules
            - /usr/src/app/client

    react-app: 
        image: psg0018/react-app
        build: ./client
        stdin_open: true
        ports: 
            - "8080:80"
        networks:
            - app-network
        volumes:
            - ./client/:/usr/src/app
            - /usr/src/app/node_modules

networks: 
    app-network:
        driver: bridge
